# Generated by Django 3.0.7 on 2021-07-29 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funsionariu', '0002_auto_20210729_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vogal',
            options={'verbose_name_plural': 'Vogal'},
        ),
        migrations.AddField(
            model_name='vogal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vogal',
            name='foto',
            field=models.ImageField(null=True, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='vogal',
            name='hashed',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vogal',
            name='naran_vogal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vogal',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
