# Generated by Django 3.0.7 on 2021-09-20 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0003_auto_20210729_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigu_unidade', models.CharField(max_length=20, null=True, unique=True)),
                ('unidade', models.CharField(max_length=100, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('vogal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.Vogal')),
            ],
            options={
                'verbose_name_plural': 'Unidade',
            },
        ),
    ]
