# Generated by Django 3.0.7 on 2021-09-20 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0004_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargu',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.Unidade'),
        ),
    ]
