# Generated by Django 3.0.7 on 2021-09-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0005_kargu_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kargu',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
