# Generated by Django 3.0.7 on 2021-10-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funsionariu', '0006_auto_20210920_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_code', models.CharField(max_length=10, verbose_name='Kodigu Kategoria')),
                ('cat_name', models.CharField(max_length=50, verbose_name='Kategoria')),
                ('hashed', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_code', models.CharField(max_length=10, verbose_name='Kodigu Sub Kategoria')),
                ('subcat_name', models.CharField(max_length=50, verbose_name='Sub Kategoria')),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Category')),
            ],
            options={
                'verbose_name_plural': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='DokumentuSai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=20, unique=True, verbose_name='Numeru Dokumentu')),
                ('subject', models.CharField(max_length=100, verbose_name='Naran Dokumentu')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('karta_ba', models.CharField(max_length=225, null=True, verbose_name='Karta ba')),
                ('folder_name', models.CharField(max_length=50, null=True)),
                ('file_name', models.FileField(max_length=200, null=True, upload_to='')),
                ('klasifikasaun', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Konfidensial', 'Konfidensial')], max_length=32, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Readed', 'Readed'), ('Done', 'Done')], max_length=20, null=True)),
                ('forward_to_president', models.BooleanField(default=False)),
                ('president_viewed', models.BooleanField(default=False)),
                ('forward_to_admin', models.BooleanField(default=False)),
                ('admin_viewed', models.BooleanField(default=False)),
                ('president_despacho', models.CharField(max_length=200, null=True)),
                ('obs', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Category')),
                ('destinu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.Diresaun')),
            ],
            options={
                'verbose_name_plural': 'Documents Sai',
            },
        ),
        migrations.CreateModel(
            name='Dokumentus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=20, unique=True, verbose_name='Numeru Dokumentu')),
                ('subject', models.CharField(max_length=100, verbose_name='Naran Dokumentu')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.CharField(max_length=225, null=True, verbose_name='Entrega Husi')),
                ('orijen', models.CharField(max_length=225, null=True, verbose_name='Orijen Dokumentu')),
                ('recieve_by', models.CharField(max_length=225, null=True, verbose_name='Simu Husi')),
                ('folder_name', models.CharField(max_length=50, null=True)),
                ('file_name', models.FileField(max_length=200, null=True, upload_to='')),
                ('klasifikasaun', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Konfidensial', 'Konfidensial')], max_length=32, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Readed', 'Readed'), ('Done', 'Done')], max_length=20, null=True)),
                ('forward_to_president', models.BooleanField(default=False)),
                ('president_viewed', models.BooleanField(default=False)),
                ('forward_to_admin', models.BooleanField(default=False)),
                ('admin_viewed', models.BooleanField(default=False)),
                ('president_despacho', models.CharField(max_length=200, null=True)),
                ('forward_to_vogal', models.BooleanField(default=False)),
                ('vogal_viewed', models.BooleanField(default=False)),
                ('forward_to_diresaun', models.BooleanField(default=False)),
                ('diretor_viewed', models.BooleanField(default=False)),
                ('obs', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Category')),
                ('destinu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.Diresaun')),
                ('president_despacho_diresaun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_diresaun', to='funsionariu.Diresaun')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Subcategory')),
            ],
            options={
                'verbose_name_plural': 'Documents Tama',
            },
        ),
    ]
