# Generated by Django 3.0.7 on 2021-11-05 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumentusai',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='dokumentusai',
            old_name='destinu',
            new_name='destination',
        ),
    ]
