# Generated by Django 3.0.7 on 2021-11-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20211104_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumentusai',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='dokumentusai',
            old_name='destination',
            new_name='destinu',
        ),
    ]
