# Generated by Django 3.0.7 on 2021-11-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0006_auto_20210920_1727'),
        ('administrator', '0003_auto_20211105_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentusai',
            name='karta_ba',
        ),
        migrations.AddField(
            model_name='dokumentusai',
            name='orijen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.Diresaun'),
        ),
        migrations.AlterField(
            model_name='dokumentusai',
            name='destinu',
            field=models.CharField(max_length=225, null=True, verbose_name='Karta ba'),
        ),
    ]
