# Generated by Django 3.0.7 on 2021-11-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20211106_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentus',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
