# Generated by Django 3.0.7 on 2021-11-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_categorydocsai'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydocsai',
            name='hashed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
