# Generated by Django 3.0.7 on 2021-11-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_categorydocsai_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentusai',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.CategoryDocSai'),
        ),
    ]
