# Generated by Django 3.0.7 on 2021-11-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20211124_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentusai',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Category'),
        ),
        migrations.DeleteModel(
            name='CategoryDocSai',
        ),
    ]
