# Generated by Django 3.0.7 on 2021-11-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20211124_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('date_respond', models.DateField()),
                ('file_name', models.FileField(max_length=200, null=True, upload_to='')),
                ('deskrisaun', models.TextField(blank=True, null=True)),
                ('karta_tama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Dokumentus')),
            ],
        ),
    ]
