# Generated by Django 3.0.7 on 2021-12-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20211202_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentusai',
            name='forward_to_vogal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokumentusai',
            name='vogal_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
