# Generated by Django 3.0.7 on 2021-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20211202_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responde',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='responde',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='dokumentus',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentusai',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
