# Generated by Django 3.0.7 on 2022-02-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0006_auto_20210920_1727'),
        ('administrator', '0013_auto_20211213_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentus',
            name='president_despacho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentus',
            name='president_despacho_diresaun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_diresaun', to='funsionariu.Diresaun'),
        ),
    ]
