# Generated by Django 3.0.7 on 2022-02-06 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20220204_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentusai',
            name='date_despacho',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
