# Generated by Django 3.0.7 on 2022-02-06 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_dokumentusai_date_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentusai',
            name='date_despacho',
        ),
        migrations.AddField(
            model_name='dokumentus',
            name='date_despacho',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
