# Generated by Django 3.0.7 on 2022-02-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_dokumentusai_diretor_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentusai',
            name='aprova',
            field=models.BooleanField(default=False),
        ),
    ]
