# Generated by Django 3.0.7 on 2022-02-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_dokumentusai_aprova'),
    ]

    operations = [
        migrations.AddField(
            model_name='responde',
            name='file_name',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
    ]
