# Generated by Django 3.0.7 on 2022-02-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_responde_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='responde',
            name='number_respond',
            field=models.CharField(default='Some String', max_length=20, unique=True, verbose_name='Numeru Responde'),
        ),
    ]
