# Generated by Django 3.0.7 on 2022-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_auto_20220219_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responde',
            old_name='file_name',
            new_name='file_respond',
        ),
        migrations.AddField(
            model_name='responde',
            name='forward_to_admin',
            field=models.BooleanField(default=False),
        ),
    ]
