# Generated by Django 3.0.7 on 2022-02-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_auto_20220219_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responde',
            old_name='number_respond',
            new_name='respond_number',
        ),
    ]
