# Generated by Django 3.0.7 on 2022-03-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0006_auto_20210920_1727'),
        ('administrator', '0026_auto_20220220_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responde',
            name='respond_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numeru Responde'),
        ),
        migrations.CreateModel(
            name='DokumentuSaiInterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=20, unique=True, verbose_name='Numeru Dokumentu')),
                ('subject', models.CharField(max_length=100, verbose_name='Naran Dokumentu')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('destinu', models.CharField(max_length=225, null=True, verbose_name='Karta ba')),
                ('folder_name', models.CharField(max_length=50, null=True)),
                ('file_name', models.FileField(max_length=200, null=True, upload_to='')),
                ('klasifikasaun', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Konfidensial', 'Konfidensial')], max_length=32, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Readed', 'Readed'), ('Done', 'Done')], max_length=20, null=True)),
                ('diretor_viewed', models.BooleanField(default=False)),
                ('forward_to_president', models.BooleanField(default=False)),
                ('president_viewed', models.BooleanField(default=False)),
                ('aprova', models.BooleanField(default=False)),
                ('forward_to_admin', models.BooleanField(default=False)),
                ('admin_viewed', models.BooleanField(default=False)),
                ('forward_to_vogal', models.BooleanField(default=False)),
                ('vogal_viewed', models.BooleanField(default=False)),
                ('president_despacho_diresaun', models.CharField(max_length=200, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Category')),
                ('orijen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.Diresaun')),
            ],
            options={
                'verbose_name_plural': 'Documents Sai Interna',
            },
        ),
    ]
