# Generated by Django 3.0.7 on 2022-03-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0006_auto_20210920_1727'),
        ('administrator', '0029_dokumentusaiinterna_president_despacho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumentusaiinterna',
            old_name='president_despacho',
            new_name='president_informa',
        ),
        migrations.RemoveField(
            model_name='dokumentusaiinterna',
            name='president_despacho_diresaun',
        ),
        migrations.AddField(
            model_name='dokumentusaiinterna',
            name='president_informa_diresaun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informa_diresaun', to='funsionariu.Diresaun'),
        ),
    ]
