# Generated by Django 3.0.7 on 2022-03-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_auto_20220321_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentusai',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='dokumentusai',
            name='president_despacho_diresaun',
        ),
    ]
