# Generated by Django 3.0.7 on 2022-03-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_auto_20220324_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentus',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='dokumentusai',
            name='aprova',
        ),
        migrations.RemoveField(
            model_name='dokumentusaiinterna',
            name='obs',
        ),
    ]
