# Generated by Django 3.0.7 on 2022-03-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_auto_20220324_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumentusaiinterna',
            old_name='forward_to_admin',
            new_name='forward_to_diresaun',
        ),
    ]
